### ISSUE TITLE
问题集中反馈区

### ISSUE THREAD

**Issue by ifeng0188** [ifeng0188/GenshinLiveStreamHelper#13]
使用本项目时遇到的各种问题，都可以在下方询问，不定时回复（已处理的小白问题会删除，以确保本页面能够快速定位问题）

**Comment by mdc987** [comment]
可以教下怎么加到油猴里嘛？油猴里直接搜没找到

**Comment by SuMingxw** [comment]
大佬可以加一下你的qq或者微信吗，我qq是3049487231

**Comment by ifeng0188** [comment]
> 大佬可以加一下你的qq或者微信吗，我qq是3049487231

不加联系方式，有问题直接这里反馈

**Comment by SuMingxw** [comment]
我这里虎牙领取时候会出现以下问题：
通行证经验领取时会出现一大堆弹窗，并且领取完通行证经验后不会点击原石领取，我后来把这些弹窗关闭后手动领取的。
弹窗内容大致是通行证经验任务未完成或者已经领取。
所以针对虎牙能否改进确认领取通行证经验后领取原石，谢谢大佬

**Comment by SuMingxw** [comment]
真的非常感谢

**Comment by ifeng0188** [comment]
> 我这里虎牙领取时候会出现以下问题： 通行证经验领取时会出现一大堆弹窗，并且领取完通行证经验后不会点击原石领取，我后来把这些弹窗关闭后手动领取的。 弹窗内容大致是通行证经验任务未完成或者已经领取。 所以针对虎牙能否改进确认领取通行证经验后领取原石，谢谢大佬

不影响的哦，这些点击动作会同时进行，包括原石的

**Comment by SuMingxw** [comment]
> > 我这里虎牙领取时候会出现以下问题： 通行证经验领取时会出现一大堆弹窗，并且领取完通行证经验后不会点击原石领取，我后来把这些弹窗关闭后手动领取的。 弹窗内容大致是通行证经验任务未完成或者已经领取。 所以针对虎牙能否改进确认领取通行证经验后领取原石，谢谢大佬
> 
> 不影响的哦，这些点击动作会同时进行，包括领取原石的

您在运行的时候是同步进行的吗，我在使用过程中确实没有自己领取原石，有点奇怪

**Comment by ifeng0188** [comment]
> > > 我这里虎牙领取时候会出现以下问题： 通行证经验领取时会出现一大堆弹窗，并且领取完通行证经验后不会点击原石领取，我后来把这些弹窗关闭后手动领取的。 弹窗内容大致是通行证经验任务未完成或者已经领取。 所以针对虎牙能否改进确认领取通行证经验后领取原石，谢谢大佬
> > 
> > 
> > 不影响的哦，这些点击动作会同时进行，包括领取原石的
> 
> 您在运行的时候是同步进行的吗，我在使用过程中确实没有自己领取原石，有点奇怪

三个定时器是同步进行的

**Comment by ifeng0188** [comment]
> > > > > 我这里虎牙领取时候会出现以下问题： 通行证经验领取时会出现一大堆弹窗，并且领取完通行证经验后不会点击原石领取，我后来把这些弹窗关闭后手动领取的。 弹窗内容大致是通行证经验任务未完成或者已经领取。 所以针对虎牙能否改进确认领取通行证经验后领取原石，谢谢大佬
> > > > 
> > > > 
> > > > 不影响的哦，这些点击动作会同时进行，包括领取原石的
> > > 
> > > 
> > > 您在运行的时候是同步进行的吗，我在使用过程中确实没有自己领取原石，有点奇怪
> > 
> > 
> > 三个定时器是同步进行的
> 
> ![}(LKP{O QW}}VA0EX2%G0{1](https://user-images.githubusercontent.com/120149825/206648963-09ff6bcd-c7a7-4d3f-8b09-14a53152a7a0.jpg) ![IYQO MD7E84(Z9SN7B}SY}6](https://user-images.githubusercontent.com/120149825/206649109-5a2df057-362c-4374-be53-7cec33cb2541.jpg) 您看下这两个图片里的领取时间，差了27秒，我发现没有领取之后手动领取的

刚刚去测试了一下，理论上来讲没有问题，三个按钮的点击确实是同时执行的。不过我这里没弄虎牙，不知道任务完成后按钮会变成什么样，所以也测试不了领取，方便的话你可以截图一下，F12打开开发者工具选中已领取按钮的dom元素。

**Comment by SuMingxw** [comment]
![~_X26ZMG~)J 61GY0GES{YQ](https://user-images.githubusercontent.com/120149825/206710431-8b97caee-6613-46e1-93c4-b7aef347f62f.png)
![UJ6 I~N}LERJ%IKTO9D({}8](https://user-images.githubusercontent.com/120149825/206710457-f9da0432-a473-4eab-96a0-12cee0c88093.png)
原石和通行证经验领取后是这样的，弹窗的按钮只能等到遇到了再截图了

**Comment by ifeng0188** [comment]
> ![_X26ZMG)J 61GY0GES{YQ](https://user-images.githubusercontent.com/120149825/206710431-8b97caee-6613-46e1-93c4-b7aef347f62f.png) ![UJ6 I~N}LERJ%IKTO9D({}8](https://user-images.githubusercontent.com/120149825/206710457-f9da0432-a473-4eab-96a0-12cee0c88093.png) 原石和通行证经验领取后是这样的，弹窗的按钮只能等到遇到了再截图了

将本项目更新到最新版试试

**Comment by SuMingxw** [comment]
> > ![_X26ZMG)J 61GY0GES{YQ](https://user-images.githubusercontent.com/120149825/206710431-8b97caee-6613-46e1-93c4-b7aef347f62f.png) ![UJ6 I~N}LERJ%IKTO9D({}8](https://user-images.githubusercontent.com/120149825/206710457-f9da0432-a473-4eab-96a0-12cee0c88093.png) 原石和通行证经验领取后是这样的，弹窗的按钮只能等到遇到了再截图了
> 
> 将本项目更新到最新版试试

好的谢谢您，测试只能等明天了

**Comment by soushua** [comment]
新手，能请教您怎么配置吗，油猴无法运行。不知道配置什么东西。

**Comment by 871943346** [comment]
虎牙会被限制领取频率导致领取不了

**Comment by tsukang** [comment]
> 虎牙会被限制领取频率导致领取不了

把脚本这行
`// 领取间隔时间（单位：毫秒 1000毫秒=1秒） PS：顺带一提，某站抢码会提示繁忙，但是这个繁忙是指服务器繁忙，一般不需要增加间隔时间
    interval: 100,`的时间改成1000

**Comment by SuShangQing** [comment]
> > 虎牙会被限制领取频率导致领取不了
> 
> 把脚本这行 `// 领取间隔时间（单位：毫秒 1000毫秒=1秒） PS：顺带一提，某站抢码会提示繁忙，但是这个繁忙是指服务器繁忙，一般不需要增加间隔时间 interval: 100,`的时间改成1000

这样改不是点击频率更高了吗

**Comment by SuShangQing** [comment]
> > > ![_X26ZMG)J 61GY0GES{YQ](https://user-images.githubusercontent.com/120149825/206710431-8b97caee-6613-46e1-93c4-b7aef347f62f.png) ![UJ6 I~N}LERJ%IKTO9D({}8](https://user-images.githubusercontent.com/120149825/206710457-f9da0432-a473-4eab-96a0-12cee0c88093.png) 原石和通行证经验领取后是这样的，弹窗的按钮只能等到遇到了再截图了
> > 
> > 
> > 将本项目更新到最新版试试
> 
> 好的谢谢您，测试只能等明天了

你好，问问可以成功领取了吗

**Comment by ifeng0188** [comment]
> 新手，能请教您怎么配置吗，油猴无法运行。不知道配置什么东西。

我只负责项目的开发，油猴的问题是油猴的问题，据我所知油猴确实有点bug

**Comment by camilleitachi** [comment]
大佬好，为什么我下载的代码的时候显示404

**Comment by SuShangQing** [comment]
> > 新手，能请教您怎么配置吗，油猴无法运行。不知道配置什么东西。
> 
> 我只负责项目的开发，油猴的问题是油猴的问题，据我所知油猴确实有点bug

大佬你好，请问我在油猴运行了最新版本的之后，并没弹出修改相应数据的提示，请问相应数据应该怎么修改呢
![image](https://user-images.githubusercontent.com/102420864/207938362-6f4fda08-32ef-412f-ab86-8b09fba73f6d.png)

**Comment by ifeng0188** [comment]
> > > 新手，能请教您怎么配置吗，油猴无法运行。不知道配置什么东西。
> > 
> > 
> > 我只负责项目的开发，油猴的问题是油猴的问题，据我所知油猴确实有点bug
> 
> 大佬你好，请问我在油猴运行了最新版本的之后，并没弹出修改相应数据的提示，请问相应数据应该怎么修改呢 ![image](https://user-images.githubusercontent.com/102420864/207938362-6f4fda08-32ef-412f-ab86-8b09fba73f6d.png)

现在升级了GUI的形式配置，如果没有，请检查你的油猴是否为最新版
![image](https://user-images.githubusercontent.com/59196138/208087789-a65c7582-bd8c-4b89-8927-d33fb63ec667.png)

**Comment by ifeng0188** [comment]
> 大佬好，为什么我下载的代码的时候显示404

网络原因，建议等一段时间再尝试，或者挂梯子

**Comment by Lulux1u** [comment]
大佬好，用你这个3.3抢到几个真的太感谢了，请问你3.4的还会更新吗

**Comment by SuShangQing** [comment]
大佬你好，3.4的斗鱼里程碑展开和净化功能好像失效了，能麻烦更新一下吗

**Comment by noneber** [comment]
大佬你好，3.4的是不是有些平台用不起了

**Comment by 871943346** [comment]
斗鱼3.4
净化和里程碑修改
![image](https://user-images.githubusercontent.com/53554546/213168079-6529b2e8-02cb-4a30-afdd-00085ee42141.png)
即将bc54改为bc68
将bc3改为bc46

**Comment by SuShangQing** [comment]
> 斗鱼3.4 净化和里程碑修改 ![image](https://user-images.githubusercontent.com/53554546/213168079-6529b2e8-02cb-4a30-afdd-00085ee42141.png) 即将bc54改为bc68 将bc3改为bc46

![image](https://user-images.githubusercontent.com/102420864/213201448-45d9d976-c36d-4310-865d-fb7346d41607.png)
这个之前是bc54也改成bc46吗

**Comment by noneber** [comment]
感谢大佬

**Comment by 123asdasdiqwneown** [comment]
![image](https://user-images.githubusercontent.com/121950539/213386267-ea03e4c6-231d-4ad4-b496-6fdb9d6d84eb.png)
大佬这样正常吗，还有b站无法启动

**Comment by memory146** [comment]
![image](https://user-images.githubusercontent.com/123110562/213526180-0cc6af59-884f-4f49-91b4-acd431206b73.png)
![image](https://user-images.githubusercontent.com/123110562/213526276-0919828c-d0d9-4547-9165-c91ecaabf42a.png)
大佬，请问是我使用方法有问题吗？

**Comment by SuShangQing** [comment]
> ![image](https://user-images.githubusercontent.com/123110562/213526180-0cc6af59-884f-4f49-91b4-acd431206b73.png) ![image](https://user-images.githubusercontent.com/123110562/213526276-0919828c-d0d9-4547-9165-c91ecaabf42a.png) 大佬，请问是我使用方法有问题吗？

你好请问一下你B站脚本有正常启动吗

**Comment by memory146** [comment]
> > ![image](https://user-images.githubusercontent.com/123110562/213526180-0cc6af59-884f-4f49-91b4-acd431206b73.png) ![image](https://user-images.githubusercontent.com/123110562/213526276-0919828c-d0d9-4547-9165-c91ecaabf42a.png) 大佬，请问是我使用方法有问题吗？
> 
> 你好请问一下你B站脚本有正常启动吗

在这个界面油猴是亮着的，但是到时间后貌似什么都没有做

**Comment by SuShangQing** [comment]
> > > ![image](https://user-images.githubusercontent.com/123110562/213526180-0cc6af59-884f-4f49-91b4-acd431206b73.png) ![image](https://user-images.githubusercontent.com/123110562/213526276-0919828c-d0d9-4547-9165-c91ecaabf42a.png) 大佬，请问是我使用方法有问题吗？
> > 
> > 
> > 你好请问一下你B站脚本有正常启动吗
> 
> 在这个界面油猴是亮着的，但是到时间后貌似什么都没有做

我也是的没有反应，能请问你最后手抢领到的吗

**Comment by memory146** [comment]
> > > > ![image](https://user-images.githubusercontent.com/123110562/213526180-0cc6af59-884f-4f49-91b4-acd431206b73.png) ![image](https://user-images.githubusercontent.com/123110562/213526276-0919828c-d0d9-4547-9165-c91ecaabf42a.png) 大佬，请问是我使用方法有问题吗？
> > > 
> > > 
> > > 你好请问一下你B站脚本有正常启动吗
> > 
> > 
> > 在这个界面油猴是亮着的，但是到时间后貌似什么都没有做
> 
> 我也是的没有反应，能请问你最后手抢领到的吗

昨天的倒是手抢到了，我第一次参加这个激励活动，应该是越到后面越难抢，真不敢说手抢得到

**Comment by geymerone** [comment]
斗鱼和b站速率都写多少啊 谁知道

**Comment by 871943346** [comment]
虎牙、斗鱼新春限时开播福利

自己找地方放

```javascript
  if (!GM_getValue("gh_newyear")) {
    GM_setValue("gh_newyear", false);
  }
  GM_registerMenuCommand(
    `${GM_getValue("gh_newyear") ? "✅" : "❌"}新春限时开播福利（点击切换）`,
    switch_newyear
  );
  function switch_newyear() {
    GM_setValue("gh_newyear", !GM_getValue("gh_newyear"));
    alert("切换成功，请刷新页面使之生效");
  }
  function run_newyear() {
    log("原神直播活动抢码助手(改):开始尝试领取新春限时开播福利");
    let timer = setInterval(() => {
      let date = new Date();
      if (
        date.getHours() == 0 &&
        date.getMinutes() == 29 &&
        date.getSeconds() >= 59
      ) {
        clearInterval(timer);
        begin_newyear();
      }
    }, 100);
    function begin_newyear() {
      log("助手开始领取新春限时开播福利，如若出现数据异常为正常情况");
      if (GM_getValue("gh_newyear")) {
        setInterval(() => {
          switch (platform) {
            case "虎牙":
              if (
                (document.querySelectorAll("div.iatzPh div")[7].innerHTML =
                  "已领取")
              ) {
                alert("已领取新春限时开播福利\n点击确定刷新页面");
                window.location.reload();
              } else {
                document.querySelectorAll("div.iatzPh div")[7].click();
                document.querySelectorAll("div.reload-item")[0].click();
                document.querySelectorAll("div.diy-popup--btn")[0].click();
              }
              break;
            case "斗鱼":
              document.querySelectorAll("#bc88")[0].click();
              if (
                (document.querySelectorAll(
                  ".wmTaskV3GiftBtn-btn"
                )[0].innerHTML = "已领取")
              ) {
                alert("已领取新春限时开播福利\n点击确定刷新页面");
                window.location.reload();
              } else {
                document.querySelectorAll(".wmTaskV3GiftBtn-btn")[0].click();
                document.querySelectorAll("button.dy-btn")[0].click();
              }
              break;
          }
        }, interval);
      }
    }
  }
```

在Run代码块加入蓝色背景代码
![1dcf76638dd905edc6f39ab3563b7cc9](https://user-images.githubusercontent.com/53554546/213954066-6a7d974f-2571-4b9e-8e91-8a1329477d90.png)



```javascript
    run_newyear();
```

**Comment by noneber** [comment]
我的b站启动后不会刷新，是要自己刷新吗

**Comment by ifeng0188** [comment]
> 我的b站启动后不会刷新，是要自己刷新吗

b站不需要刷新页面就可以一直执行领取（过年在老家所以没及时回复）

**Comment by ifeng0188** [comment]
> 斗鱼和b站速率都写多少啊 谁知道

不懂的话默认即可（过年在老家所以没及时回复）

**Comment by ifeng0188** [comment]
> ![image](https://user-images.githubusercontent.com/123110562/213526180-0cc6af59-884f-4f49-91b4-acd431206b73.png) ![image](https://user-images.githubusercontent.com/123110562/213526276-0919828c-d0d9-4547-9165-c91ecaabf42a.png) 大佬，请问是我使用方法有问题吗？

从图片上来看，程序是已经执行了（过年在老家所以没及时回复）

**Comment by ifeng0188** [comment]
> 大佬好，用你这个3.3抢到几个真的太感谢了，请问你3.4的还会更新吗

偶尔有空就更新更新，这个isuse里面也有其他人发新版本解决方案，可以参考参考（过年在老家所以没及时回复）

**Comment by ifeng0188** [comment]
> ![image](https://user-images.githubusercontent.com/121950539/213386267-ea03e4c6-231d-4ad4-b496-6fdb9d6d84eb.png) 大佬这样正常吗，还有b站无法启动

b站需要点进兑换页面哦（过年在老家所以没及时回复）

**Comment by liuzj288** [comment]
能不能为三个网站分别加个开关，比如斗鱼现在验证码基本无解，我想关闭斗鱼功能目前只能开无痕模式

**Comment by ifeng0188** [comment]
> 能不能为三个网站分别加个开关，比如斗鱼现在验证码基本无解，我想关闭斗鱼功能目前只能开无痕模式

可以的，不过要等周末了，最近没电脑

**Comment by JunzheQoQ** [comment]
大佬！今天出3.5版本了！有空的话可以更新下嘛？万分感谢！！！！跪求QAQ

**Comment by ifeng0188** [comment]
> 大佬！今天出3.5版本了！有空的话可以更新下嘛？万分感谢！！！！跪求QAQ

自动兼容的

**Comment by Lulux1u** [comment]
大佬！3.5版本的斗鱼直播间优化又失效了，是又要重新调整参数嘛咱不会啊，能麻烦你有空弄一下吗感谢

**Comment by ifeng0188** [comment]
> 大佬！3.5版本的斗鱼直播间优化又失效了，是又要重新调整参数嘛咱不会啊，能麻烦你有空弄一下吗感谢

要星期六啦，最早也要星期五
