### ISSUE TITLE
大佬好，请问下斗鱼现在是不是不能运行这个了，他现在必须验证完一个语序验证码才能领到，点别的材料也没法提前刷不掉，虎牙的话好像有的时候不会自动运行抢码

### ISSUE THREAD

**Issue by Lulux1u** [ifeng0188/GenshinLiveStreamHelper#17]

**Comment by ifeng0188** [comment]
我自己是不抢的，只负责项目的维护，毕竟免费开源的项目，具体情况你要问他们的

**Comment by Lulux1u** [comment]
感谢回复！那请问大佬可以试着看能做一个斗鱼无视或者跳过验证码直接抢的功能吗，您可以定价我爱发电赞助您

**Comment by ifeng0188** [comment]
> 感谢回复！那请问大佬可以试着看能做一个斗鱼无视或者跳过验证码直接抢的功能吗，您可以定价我爱发电赞助您

不考虑，验证码有特殊方法可以提前过掉，具体自己研究

**Comment by noneber** [comment]
.
