### ISSUE TITLE
大佬你好，虎牙平台有时候会出现只领取经验但是没有领取奖励的情况，想请问一下是领取频率过快的原因吗

### ISSUE THREAD

**Issue by SuShangQing** [ifeng0188/GenshinLiveStreamHelper#6]
![(CU3NUA)K55W{2UDEVV7`5Y](https://user-images.githubusercontent.com/102420864/195965465-8f153036-137d-40e8-9a56-8f1c3ddd0994.png)

**Comment by ifeng0188** [comment]
请检查自己的里程碑是否配置正确

**Comment by SuShangQing** [comment]
我应该配置正确了，那我下次试试，okk

**Comment by miracle741** [comment]
兄弟你领到了吗，我好几次没领到了
