### ISSUE TITLE
虎牙的奖励领不到了

### ISSUE THREAD

**Issue by miracle741** [ifeng0188/GenshinLiveStreamHelper#7]
<img width="462" alt="捕获" src="https://user-images.githubusercontent.com/109858103/197356022-a2bf237c-03ca-4bd9-bb55-0b8484794215.PNG">
不知道其他人有没有这个问题，已经连续三次没领到了。。。。只有虎牙有这个问题

**Comment by ifeng0188** [comment]
听说虎牙限制频率了，我自己没抢不清楚

**Comment by miracle741** [comment]
> 听说虎牙限制频率了，我自己没抢不清楚

好吧，那就没办法了

**Comment by SuShangQing** [comment]
> > 听说虎牙限制了，我自己没有抢购
> 
> 好吧，那就没办法了

你好，问问B站每次都能正常抢到了，我频率100有几次抢不到，问问影应该设置成多少比较合适
